In [2]:
from transformers import TFBertModel, BertTokenizer

In [3]:
model_name = "bert-large-uncased"

In [4]:
model = TFBertModel.from_pretrained(model_name)

/usr/local/lib/python3.11/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning: 
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(


config.json:   0%|          | 0.00/571 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/1.34G [00:00<?, ?B/s]

Some weights of the PyTorch model were not used when initializing the TF 2.0 model TFBertModel: ['cls.seq_relationship.bias', 'cls.seq_relationship.weight', 'cls.predictions.transform.dense.weight', 'cls.predictions.transform.LayerNorm.bias', 'cls.predictions.transform.LayerNorm.weight', 'cls.predictions.bias', 'cls.predictions.transform.dense.bias']
- This IS expected if you are initializing TFBertModel from a PyTorch model trained on another task or with another architecture (e.g. initializing a TFBertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing TFBertModel from a PyTorch model that you expect to be exactly identical (e.g. initializing a TFBertForSequenceClassification model from a BertForSequenceClassification model).
All the weights of TFBertModel were initialized from the PyTorch model.
If your task is similar to the task the model of the checkpoint was trained on, you can already use TFBertModel for predictions w

In [5]:
tokenizer = BertTokenizer.from_pretrained(model_name)

tokenizer_config.json:   0%|          | 0.00/48.0 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

In [6]:
sentence1 = "I engoy learning AI and ML"
sentence2 = "I love coding and programming"

In [8]:
tokens1 = tokenizer(sentence1, return_tensors="tf")
tokens2 = tokenizer(sentence2, return_tensors="tf")
tokens1,tokens2

({'input_ids': <tf.Tensor: shape=(1, 9), dtype=int32, numpy=
 array([[  101,  1045, 25540,  6977,  4083,  9932,  1998, 19875,   102]],
       dtype=int32)>, 'token_type_ids': <tf.Tensor: shape=(1, 9), dtype=int32, numpy=array([[0, 0, 0, 0, 0, 0, 0, 0, 0]], dtype=int32)>, 'attention_mask': <tf.Tensor: shape=(1, 9), dtype=int32, numpy=array([[1, 1, 1, 1, 1, 1, 1, 1, 1]], dtype=int32)>},
 {'input_ids': <tf.Tensor: shape=(1, 7), dtype=int32, numpy=array([[  101,  1045,  2293, 16861,  1998,  4730,   102]], dtype=int32)>, 'token_type_ids': <tf.Tensor: shape=(1, 7), dtype=int32, numpy=array([[0, 0, 0, 0, 0, 0, 0]], dtype=int32)>, 'attention_mask': <tf.Tensor: shape=(1, 7), dtype=int32, numpy=array([[1, 1, 1, 1, 1, 1, 1]], dtype=int32)>})

In [9]:
embeddings1 = model(tokens1)["last_hidden_state"]
embeddings2 = model(tokens2)["last_hidden_state"]
embeddings1,embeddings2

(<tf.Tensor: shape=(1, 9, 1024), dtype=float32, numpy=
 array([[[-0.1397298 , -0.72077066, -0.18522057, ..., -0.7099822 ,
          -0.62937915,  0.2713756 ],
         [-0.18416613, -0.43161476,  0.19692469, ..., -0.15077743,
           0.07257618,  0.32102942],
         [-0.40386486, -0.15967211,  0.5909412 , ..., -0.23652932,
           0.13751802, -0.3445388 ],
         ...,
         [-0.29053965,  0.05978524,  0.09575465, ..., -1.2215334 ,
          -1.6667573 ,  0.09693614],
         [-0.12688152, -0.26206762,  0.17964573, ...,  0.21009155,
          -0.43638644, -0.2016815 ],
         [-0.46832812, -0.01146339,  0.12078212, ..., -1.1369388 ,
          -1.1399636 , -0.30037546]]], dtype=float32)>,
 <tf.Tensor: shape=(1, 7, 1024), dtype=float32, numpy=
 array([[[-0.35758382, -0.37965894, -0.55130947, ..., -0.6323968 ,
          -0.5696004 , -0.01382361],
         [-0.08043627, -0.3108411 , -0.3577851 , ..., -0.01366018,
           0.06876336,  0.06242287],
         [-0.5625444 , -0

In [10]:
import numpy as np
mean_embeddings1 = np.mean(embeddings1, axis=1)
mean_embeddings2 = np.mean(embeddings2, axis=1)
mean_embeddings1,mean_embeddings2

(array([[-0.29248402, -0.22823614,  0.13675234, ..., -0.3821273 ,
         -0.35507354,  0.04548408]], dtype=float32),
 array([[-0.22878681, -0.16270329, -0.40741864, ..., -0.176802  ,
         -0.19280896,  0.04269575]], dtype=float32))

In [11]:
from sklearn.metrics.pairwise import cosine_similarity
similarity = cosine_similarity(mean_embeddings1, mean_embeddings2)
print("Cosine Similarity:", similarity)

Cosine Similarity: [[0.6249778]]


In [16]:
sentence1 = "I love programming"
sentence2 = "This movie is too bad"


tokens1 = tokenizer(sentence1, return_tensors="tf")
tokens2 = tokenizer(sentence2, return_tensors="tf")
# إيجاد تضمين مفردات كل جملة
embeddings1 = model(tokens1)["last_hidden_state"]
embeddings2 = model(tokens2)["last_hidden_state"]


import numpy as np
mean_embeddings1 = np.mean(embeddings1, axis=1)
mean_embeddings2 = np.mean(embeddings2, axis=1)


from sklearn.metrics.pairwise import cosine_similarity
similarity = cosine_similarity(mean_embeddings1, mean_embeddings2)

print("Cosine Similarity:", similarity)

Cosine Similarity: [[0.34937447]]
